---
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    path: /dashboard

management:
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  health:
    defaults:
      enabled: true

logging:
  pattern:
    level: "[%X{data}%thread] [%X{X-B3-TraceId:-}] - %5p"
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.cloud.config.server: INFO
    org.springframework.web: INFO
    org.springframework.web.client: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    com.jdhv: DEBUG
